# Generated by Django 4.1.3 on 2022-11-21 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeightInfo', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('WeightIngo', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('AgeInfo', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('BloodGroupInfo', models.CharField(max_length=3, null=True)),
                ('publications', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
