# Generated by Django 4.1.3 on 2022-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAllergen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallergenclass',
            name='AllergenImportant',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
